### ISSUE TITLE
Who can provide a cookie?I am a foreigner,pls

### ISSUE THREAD

**Issue by hrzblog** [honey720/chzzk-vod-downloader-v2#1]
I can pay for  it

**Comment by honey720** [comment]
If you have a Korean phone number in your name, you can use cookies on your Naver account even if you are a foreigner.

**Comment by hrzblog** [comment]
> Hi If you have a Korean phone number in your name, you can use cookies on your Naver account even if you are a foreigner.

It is so hard.I even don't have a passport.I can't register a Korea phone number,do you have any other ways?

**Comment by honey720** [comment]
Hi. There is no way I can help you.

**Comment by honey720** [comment]
> > Hi If you have a Korean phone number in your name, you can use cookies on your Naver account even if you are a foreigner.
> 
> It is so hard.I even don't have a passport.I can't register a Korea phone number,do you have any other ways?

There is no way I can help you.
