### ISSUE TITLE
Error occurred while fetching resolutions

### ISSUE THREAD

**Issue by hhh3131313** [honey720/chzzk-vod-downloader-v2#2]
404 Client error: Not found for url https://apis.naver.com
![925020036](https://github.com/user-attachments/assets/11229174-23f8-46f3-81fc-cfb98653b268)

**Comment by hhh31313** [comment]
It's working well right now

**Comment by honey720** [comment]
@hhh3131313 
This may be due to a temporary error in the API server. Please try again in a moment. If this problem occurs again, please let me know again.

**Comment by hhh31313** [comment]
> @hhh3131313 
> This may be due to a temporary error in the API server. Please try again in a moment. If this problem occurs again, please let me know again.

Yes,you're right. It's working now.
